// FIX: Import OrderFlowStatus and DeliveryLocation types
import { Restaurant, RiderJob, MenuItem, Order, OrderFlowStatus, Bilingual, DeliveryLocation } from './types';
import { SelfLogo, SharifFastFoodLogo, SharifPlusLogo, ClunaLogo, CleanFoodLogo } from './components/Logos';

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'self',
    name: { en: 'Self Service', fa: 'سلف دانشگاه' },
    type: 'self-service',
    logo: SelfLogo,
    categories: { en: ['Iranian'], fa: ['ایرانی'] },
    popularity: 9,
  },
  {
    id: 'sharif-fast-food',
    name: { en: 'Sharif Fast Food', fa: 'شریف فست فود' },
    type: 'menu',
    logo: SharifFastFoodLogo,
    categories: { en: ['Pizza', 'Pasta', 'Burgers', 'Sandwiches', 'Appetizers', 'Breakfast'], fa: ['پیتزا', 'پاستا', 'برگرها', 'ساندویچ‌ها', 'پیش غذا', 'صبحانه'] },
    popularity: 8,
    menu: [
      {
        title: { en: 'Pizza', fa: 'پیتزا' },
        items: [
          { id: 'sff-p1', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Special Pizza', fa: 'پیتزا مخصوص' }, price: 215000, popularity: 7 },
          { id: 'sff-p2', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Mixed Pizza', fa: 'پیتزا مخلوط' }, price: 190000, popularity: 8 },
          { id: 'sff-p3', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Pepperoni Pizza', fa: 'پیتزا پپرونی' }, price: 190000, popularity: 9 },
          { id: 'sff-p4', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Meat & Mushroom Pizza', fa: 'پیتزا گوشت و قارچ' }, price: 210000, popularity: 8 },
          { id: 'sff-p5', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Roast Beef Pizza', fa: 'پیتزا رست بیف' }, price: 210000, popularity: 7 },
          { id: 'sff-p6', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Chicken Alfredo Pizza', fa: 'پیتزا چیکن آلفردو' }, price: 200000, popularity: 6 },
          { id: 'sff-p7', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Vegetable Pizza', fa: 'پیتزا سبزیجات' }, price: 170000, popularity: 5 },
          { id: 'sff-p8', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Garlic & Steak Pizza', fa: 'پیتزا سیر و استیک' }, price: 230000, popularity: 9 },
          { id: 'sff-p9', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Bacon Pizza', fa: 'پیتزا بیکن' }, price: 215000, popularity: 7 },
        ],
      },
      {
        title: { en: 'Pasta', fa: 'پاستا' },
        items: [
          { id: 'sff-pa1', restaurantId: 'sharif-fast-food', category: { en: 'Pasta', fa: 'پاستا' }, name: { en: 'Special Cheese Pasta', fa: 'چیز پاستا مخصوص' }, price: 200000, popularity: 7 },
          { id: 'sff-pa2', restaurantId: 'sharif-fast-food', category: { en: 'Pasta', fa: 'پاستا' }, name: { en: 'Chicken Alfredo Pasta', fa: 'پاستا چیکن آلفردو' }, price: 180000, popularity: 6 },
        ],
      },
      {
        title: { en: 'Burgers', fa: 'برگرها' },
        items: [
          { id: 'sff-b1', restaurantId: 'sharif-fast-food', category: { en: 'Burgers', fa: 'برگرها' }, name: { en: 'Cheese Burger', fa: 'چیز برگر' }, price: 190000, popularity: 8 },
          { id: 'sff-b2', restaurantId: 'sharif-fast-food', category: { en: 'Burgers', fa: 'برگرها' }, name: { en: 'Charcoal Burger', fa: 'همبرگر ذغالی' }, price: 170000, popularity: 7 },
          { id: 'sff-b3', restaurantId: 'sharif-fast-food', category: { en: 'Burgers', fa: 'برگرها' }, name: { en: 'Chicken Burger', fa: 'چیکن برگر' }, price: 210000, popularity: 6 },
          { id: 'sff-b4', restaurantId: 'sharif-fast-food', category: { en: 'Burgers', fa: 'برگرها' }, name: { en: 'Mushroom Burger', fa: 'ماش روم برگر' }, price: 185000, popularity: 5 },
        ],
      },
      {
        title: { en: 'Sandwiches', fa: 'ساندویچ‌ها' },
        items: [
          { id: 'sff-s1', restaurantId: 'sharif-fast-food', category: { en: 'Sandwiches', fa: 'ساندویچ‌ها' }, name: { en: 'Falafel', fa: 'فلافل' }, price: 100000, popularity: 9 },
          { id: 'sff-s2', restaurantId: 'sharif-fast-food', category: { en: 'Sandwiches', fa: 'ساندویچ‌ها' }, name: { en: 'Hot Dog', fa: 'هات داگ' }, price: 140000, popularity: 7 },
          { id: 'sff-s3', restaurantId: 'sharif-fast-food', category: { en: 'Sandwiches', fa: 'ساندویچ‌ها' }, name: { en: 'Bandari', fa: 'بندری' }, price: 110000, popularity: 6 },
          { id: 'sff-s4', restaurantId: 'sharif-fast-food', category: { en: 'Sandwiches', fa: 'ساندویچ‌ها' }, name: { en: 'Grilled Chicken', fa: 'مرغ گریل' }, price: 155000, popularity: 8 },
          { id: 'sff-s5', restaurantId: 'sharif-fast-food', category: { en: 'Sandwiches', fa: 'ساندویچ‌ها' }, name: { en: 'Doner Kebab Meat', fa: 'دونر کباب گوشت' }, price: 185000, popularity: 7 },
          { id: 'sff-s6', restaurantId: 'sharif-fast-food', category: { en: 'Sandwiches', fa: 'ساندویچ‌ها' }, name: { en: 'Baked Ham', fa: 'ژامبون تنوری' }, price: 185000, popularity: 6 },
        ],
      },
      {
        title: { en: 'Appetizers', fa: 'پیش غذا' },
        items: [
          { id: 'sff-a1', restaurantId: 'sharif-fast-food', category: { en: 'Appetizers', fa: 'پیش غذا' }, name: { en: 'Garlic Bread', fa: 'نان سیر' }, price: 120000, popularity: 8 },
          { id: 'sff-a2', restaurantId: 'sharif-fast-food', category: { en: 'Appetizers', fa: 'پیش غذا' }, name: { en: 'French Fries', fa: 'سیب زمینی' }, price: 85000, popularity: 9 },
          { id: 'sff-a3', restaurantId: 'sharif-fast-food', category: { en: 'Appetizers', fa: 'پیش غذا' }, name: { en: 'Special French Fries', fa: 'سیب زمینی مخصوص' }, price: 140000, popularity: 7 },
          { id: 'sff-a4', restaurantId: 'sharif-fast-food', category: { en: 'Appetizers', fa: 'پیش غذا' }, name: { en: 'French Fries with Mushroom Sauce', fa: 'سیب زمینی با سس قارچ' }, price: 150000, popularity: 6 },
          { id: 'sff-a5', restaurantId: 'sharif-fast-food', category: { en: 'Appetizers', fa: 'پیش غذا' }, name: { en: 'Chips & Cheese', fa: 'چیپس و پنیر' }, price: 120000, popularity: 8 },
        ],
      },
      {
        title: { en: 'Breakfast', fa: 'صبحانه' },
        items: [
          { id: 'sff-bf1', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Fried Egg', fa: 'نیمرو' }, price: 55000, popularity: 7 },
          { id: 'sff-bf2', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Omelette', fa: 'املت' }, price: 60000, popularity: 8 },
          { id: 'sff-bf3', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Sausage & Egg', fa: 'سوسیس تخم مرغ' }, price: 65000, popularity: 7 },
          { id: 'sff-bf4', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Mushroom Omelette', fa: 'املت قارچ' }, price: 70000, popularity: 6 },
          { id: 'sff-bf5', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Sausage Omelette', fa: 'سوسیس املت' }, price: 75000, popularity: 7 },
          { id: 'sff-bf6', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Cheese Omelette', fa: 'چیز املت' }, price: 65000, popularity: 8 },
          { id: 'sff-bf7', restaurantId: 'sharif-fast-food', category: { en: 'Breakfast', fa: 'صبحانه' }, name: { en: 'Super Omelette', fa: 'سوپر املت' }, price: 85000, popularity: 9 },
        ],
      },
    ],
  },
  {
    id: 'sharif-plus',
    name: { en: 'Sharif Plus', fa: 'شریف پلاس' },
    type: 'menu',
    logo: SharifPlusLogo,
    categories: { en: ['Cafe', 'Salad', 'Pizza', 'Fast Food', 'Iranian'], fa: ['کافه', 'سالاد', 'پیتزا', 'فست فود', 'ایرانی'] },
    popularity: 10,
    menu: [
      {
        title: { en: 'Cafe', fa: 'کافه' },
        items: [
          { id: 'sp-c1', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Cappuccino', fa: 'آیس کاپوچینو' }, price: 120000, popularity: 7 },
          { id: 'sp-c2', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Cafe Latte', fa: 'آیس کافه لاته' }, price: 120000, popularity: 8 },
          { id: 'sp-c3', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Cake of the Day', fa: 'کیک روز' }, price: 85000, popularity: 6 },
          { id: 'sp-c4', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Special Cake', fa: 'کیک ویژه' }, price: 110000, popularity: 7 },
          { id: 'sp-c5', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Cheesecake', fa: 'چیزکیک' }, price: 105000, popularity: 9 },
          { id: 'sp-c6', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Chises & Cheesecake', fa: 'چیسسس و چیزکیک' }, price: 90000, popularity: 5 },
          { id: 'sp-c7', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Special Chises & Cheesecake', fa: 'چیسسس و چیزکیک ویژه' }, price: 150000, popularity: 8 },
          { id: 'sp-c8', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Nescafe Shake', fa: 'شیک نسکافه' }, price: 130000, popularity: 7 },
          { id: 'sp-c9', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Americano', fa: 'آیس آمریکانو' }, price: 120000, popularity: 7 },
          { id: 'sp-c10', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Mocha', fa: 'آیس موکا' }, price: 120000, popularity: 7 },
          { id: 'sp-c11', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Latte', fa: 'آیس لاته' }, price: 120000, popularity: 7 },
          { id: 'sp-c12', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Espresso', fa: 'آیس اسپرسو' }, price: 120000, popularity: 7 },
          { id: 'sp-c13', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Vanilla', fa: 'آیس وانیل' }, price: 120000, popularity: 7 },
          { id: 'sp-c14', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Chocolate', fa: 'آیس شکلات' }, price: 120000, popularity: 7 },
        ],
      },
      {
        title: { en: 'Salad Bar', fa: 'سالاد بار' },
        items: [
          { id: 'sp-sa1', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Yogurt Salad', fa: 'سالاد ماست' }, price: 35000, popularity: 6 },
          { id: 'sp-sa2', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Green Salad', fa: 'سالاد سبز' }, price: 80000, popularity: 7 },
          { id: 'sp-sa3', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Cucumber Salad', fa: 'سالاد خیار' }, price: 80000, popularity: 5 },
          { id: 'sp-sa4', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Cabbage Salad', fa: 'سالاد کلم' }, price: 85000, popularity: 6 },
          { id: 'sp-sa5', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Lettuce & Yogurt Salad', fa: 'سالاد کاهو و ماست' }, price: 35000, popularity: 5 },
          { id: 'sp-sa6', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Chicken Salad', fa: 'سالاد مرغ' }, price: 100000, popularity: 8 },
          { id: 'sp-sa7', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Tuna Salad', fa: 'سالاد تن ماهی' }, price: 100000, popularity: 7 },
          { id: 'sp-sa8', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Greek Salad', fa: 'سالاد یونانی' }, price: 100000, popularity: 8 },
          { id: 'sp-sa9', restaurantId: 'sharif-plus', category: { en: 'Salad', fa: 'سالاد' }, name: { en: 'Vegetable/Seasonal Salad', fa: 'سالاد سبزیجات / فصل' }, price: 80000, popularity: 7 },
        ],
      },
      {
        title: { en: 'Pizza', fa: 'پیتزا' },
        items: [
          { id: 'sp-p1', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Meat Pizza', fa: 'پیتزا گوشت' }, price: 420000, popularity: 9 },
          { id: 'sp-p2', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Chicken Pizza', fa: 'پیتزا مرغ' }, price: 370000, popularity: 8 },
          { id: 'sp-p3', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Mixed Pizza', fa: 'پیتزا مخلوط' }, price: 420000, popularity: 9 },
          { id: 'sp-p4', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Simple Pizza', fa: 'پیتزا ساده' }, price: 85000, popularity: 6 },
          { id: 'sp-p5', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Mushroom Pizza', fa: 'پیتزا قارچ' }, price: 100000, popularity: 7 },
          { id: 'sp-p6', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Sausage Pizza', fa: 'پیتزا سوسیس' }, price: 85000, popularity: 6 },
          { id: 'sp-p7', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Salami Pizza', fa: 'پیتزا کالباس' }, price: 140000, popularity: 7 },
          { id: 'sp-p8', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Simple Mixed Pizza', fa: 'پیتزا مخلوط ساده' }, price: 85000, popularity: 6 },
          { id: 'sp-p9', restaurantId: 'sharif-plus', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Mushroom Mixed Pizza', fa: 'پیتزا قارچ مخلوط' }, price: 140000, popularity: 7 },
        ],
      },
      {
        title: { en: 'Fast Food / Snack', fa: 'فست فود / اسنک' },
        items: [
          { id: 'sp-fs1', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Meat Snack', fa: 'اسنک گوشت' }, price: 230000, popularity: 8 },
          { id: 'sp-fs2', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Chicken Snack', fa: 'اسنک مرغ' }, price: 230000, popularity: 7 },
          { id: 'sp-fs3', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Chicken Penne Pasta', fa: 'پاستا پنه مرغ' }, price: 250000, popularity: 8 },
          { id: 'sp-fs4', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Meat Penne Pasta', fa: 'پاستا پنه گوشت' }, price: 275000, popularity: 9 },
          { id: 'sp-fs5', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Alfredo Pasta', fa: 'پاستا آلفردو' }, price: 285000, popularity: 8 },
          { id: 'sp-fs6', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Special Pasta', fa: 'پاستا اسپیشال' }, price: 285000, popularity: 7 },
          { id: 'sp-fs7', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Garlic & Vegetable Pizza', fa: 'پیتزا سیر و سبزیجات' }, price: 399000, popularity: 9 },
          { id: 'sp-fs8', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Meat Sausage', fa: 'سوسیس گوشت' }, price: 265000, popularity: 6 },
          { id: 'sp-fs9', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Chicken Sausage', fa: 'سوسیس مرغ' }, price: 250000, popularity: 5 },
          { id: 'sp-fs10', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Double Burger', fa: 'دوبل برگر' }, price: 275000, popularity: 8 },
          { id: 'sp-fs11', restaurantId: 'sharif-plus', category: { en: 'Fast Food', fa: 'فست فود' }, name: { en: 'Royal Burger', fa: 'رویال برگر' }, price: 250000, popularity: 7 },
        ],
      },
      {
        title: { en: 'Iranian Food', fa: 'غذای ایرانی' },
        items: [
          { id: 'sp-i1', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Omelette', fa: 'املت' }, price: 75000, popularity: 7 },
          { id: 'sp-i2', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Apple & Spinach Stew', fa: 'سیب و اسفناج' }, price: 75000, popularity: 6 },
          { id: 'sp-i3', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Bean Stew', fa: 'خوراک لوبیا چیتی' }, price: 75000, popularity: 7 },
          { id: 'sp-i4', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Meat & Mushroom', fa: 'گوشت و قارچ' }, price: 65000, popularity: 8 },
          { id: 'sp-i5', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Breakfast', fa: 'صبحانه' }, price: 65000, popularity: 7 },
          { id: 'sp-i6', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Chicken Koobideh', fa: 'کوبیده مرغ' }, price: 165000, popularity: 9 },
          { id: 'sp-i7', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Meat Koobideh', fa: 'کوبیده گوشت' }, price: 240000, popularity: 9 },
          { id: 'sp-i8', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Gheimeh Stew', fa: 'خورشت قیمه' }, price: 260000, popularity: 8 },
          { id: 'sp-i9', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Ghormeh Sabzi Stew', fa: 'قورمه سبزی' }, price: 260000, popularity: 9 },
          { id: 'sp-i10', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Fesenjan Stew', fa: 'فسنجان' }, price: 260000, popularity: 7 },
          { id: 'sp-i11', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Karafsi Stew', fa: 'خورشت کرفس' }, price: 180000, popularity: 6 },
          { id: 'sp-i12', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Okra Stew', fa: 'خورشت بامیه' }, price: 180000, popularity: 5 },
          { id: 'sp-i13', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Plum Stew', fa: 'خورشت آلو' }, price: 180000, popularity: 6 },
          { id: 'sp-i14', restaurantId: 'sharif-plus', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Vegetable Stew', fa: 'خورشت سبزیجات' }, price: 170000, popularity: 7 },
        ],
      },
    ],
  },
  {
    id: 'cluna',
    name: { en: 'CLUNA', fa: 'کلانا' },
    type: 'external',
    logo: ClunaLogo,
    categories: { en: ['Sandwich', 'Snacks'], fa: ['ساندویچ', 'اسنک'] },
    url: 'https://pwa.cluna.app/main',
    popularity: 7,
  },
  {
    id: 'cleanfoods',
    name: { en: 'CleanFoods', fa: 'کلین فودز' },
    type: 'external',
    logo: CleanFoodLogo,
    categories: { en: ['Salad', 'Healthy'], fa: ['سالاد', 'سلامت'] },
    url: 'https://order.cleanfoods.ir/order/cleanfood-sharif-university',
    popularity: 6,
  },
];

export const ALL_ITEMS: MenuItem[] = RESTAURANTS.flatMap(r => r.menu ? r.menu.flatMap(c => c.items) : []);

export const SELF_SERVICE_DATA = {
    food: [
        { id: 'self-f1', restaurantId: 'self', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Gheimeh', fa: 'قیمه' }, price: 80000, popularity: 8 },
        { id: 'self-f2', restaurantId: 'self', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Ghormeh Sabzi', fa: 'قورمه سبزی' }, price: 80000, popularity: 9 },
        { id: 'self-f3', restaurantId: 'self', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Chicken', fa: 'مرغ' }, price: 90000, popularity: 7 },
    ],
    drinks: [
        { id: 'self-d1', restaurantId: 'self', category: { en: 'Drinks', fa: 'نوشیدنی' }, name: { en: 'Sprite', fa: 'اسپرایت' }, price: 20000, popularity: 5 },
        { id: 'self-d2', restaurantId: 'self', category: { en: 'Drinks', fa: 'نوشیدنی' }, name: { en: 'Doogh', fa: 'دوغ' }, price: 20000, popularity: 7 },
        { id: 'self-d3', restaurantId: 'self', category: { en: 'Drinks', fa: 'نوشیدنی' }, name: { en: 'Yogurt', fa: 'ماست' }, price: 20000, popularity: 6 },
        { id: 'self-d4', restaurantId: 'self', category: { en: 'Drinks', fa: 'نوشیدنی' }, name: { en: 'Lemonade', fa: 'لیموناد' }, price: 20000, popularity: 4 },
        { id: 'self-d5', restaurantId: 'self', category: { en: 'Drinks', fa: 'نوشیدنی' }, name: { en: 'Coca-Cola', fa: 'کوکاکولا' }, price: 20000, popularity: 9 },
        { id: 'self-d6', restaurantId: 'self', category: { en: 'Drinks', fa: 'نوشیدنی' }, name: { en: 'Zero', fa: 'زیرو' }, price: 20000, popularity: 8 },
    ],
    addOns: [
        { id: 'self-a1', restaurantId: 'self', category: { en: 'Add-ons', fa: 'افزودنی‌ها' }, name: { en: 'Container', fa: 'ظرف' }, price: 4000, popularity: 5 },
        { id: 'self-a2', restaurantId: 'self', category: { en: 'Add-ons', fa: 'افزودنی‌ها' }, name: { en: 'Spoon & Fork', fa: 'قاشق و چنگال' }, price: 4000, popularity: 6 },
    ],
    halls: [
        { en: 'Girls Hall', fa: 'سالن سلف دختران' },
        { en: 'Boys Hall', fa: 'سالن سلف پسران' },
    ],
};

export const MOCK_RIDER_JOBS: RiderJob[] = [
    { id: 'job-1', orderId: 'SHF-20231027-A1B2', status: 'pending', restaurantName: {en: "Self Service", fa: 'سلف دانشگاه'}, pickup: 'Self Service Kitchen', destination: 'Boys Hall', items: 'Ghormeh Sabzi, Doogh', timestamps: {}, isRequest: false },
    { id: 'job-2', requestId: 'req_12345', status: 'pending', restaurantName: {en: "Cluna", fa: 'کلانا'}, pickup: 'Cluna Stall', destination: 'Main Library Entrance', items: 'Chicken Pesto Sandwich', timestamps: {}, isRequest: true },
    { id: 'job-3', orderId: 'SHF-20231027-C3D4', status: 'accepted', riderId: 'rider-007', restaurantName: {en: "Sharif Fast Food", fa: 'شریف فست فود'}, pickup: 'Sharif Fast Food Counter', destination: 'Computer Engineering Faculty', items: '2x Pepperoni Pizza', timestamps: { accepted: Date.now() }, isRequest: false },
];

export const MOCK_CUSTOMER_ORDERS: Order[] = [
    {
        id: 'cust-order-001',
        code: 'CUST-A1B2',
        userId: 'user-123',
        items: [{ id: 'sff-p1', restaurantId: 'sharif-fast-food', category: { en: 'Pizza', fa: 'پیتزا' }, name: { en: 'Vegetable Pizza', fa: 'پیتزا سبزیجات' }, price: 170000, quantity: 1 }],
        deliveryFee: 30000,
        total: 195000,
        status: OrderFlowStatus.PAYMENT_CONFIRMED,
        timestamp: Date.now() - 3600000, // 1 hour ago
        restaurantName: { en: 'Sharif Fast Food', fa: 'شریف فست فود' },
        customerNotes: 'Deliver to 3rd floor, room 305.',
        customerPhone: '09123456789',
        deliveryLocation: { id: 'energy-faculty', name: { en: 'Energy Engineering Faculty', fa: 'دانشکده مهندسی انرژی' }, fee: 30000 },
        promoCodeApplied: 'SHARIFTEST',
        discountAmount: 5000,
    },
    {
        id: 'cust-order-002',
        code: 'CUST-C3D4',
        userId: 'user-123',
        items: [{ id: 'sp-c1', restaurantId: 'sharif-plus', category: { en: 'Cafe', fa: 'کافه' }, name: { en: 'Iced Cappuccino', fa: 'آیس کاپوچینو' }, price: 120000, quantity: 2 }],
        deliveryFee: 20000,
        total: 265000,
        status: OrderFlowStatus.AWAITING_PAYMENT,
        timestamp: Date.now() - 1800000, // 30 mins ago
        restaurantName: { en: 'Sharif Plus', fa: 'شریف پلاس' },
        customerNotes: 'Please ring the bell twice.',
        customerPhone: '09121112233',
        deliveryLocation: { id: 'computer-faculty', name: { en: 'Computer Engineering Faculty', fa: 'دانشکده مهندسی کامپیوتر' }, fee: 15000 },
    },
    {
        id: 'cust-order-003',
        code: 'CUST-E5F6',
        userId: 'user-123',
        items: [{ id: 'self-f1', restaurantId: 'self', category: { en: 'Iranian', fa: 'ایرانی' }, name: { en: 'Gheimeh', fa: 'قیمه' }, price: 80000, quantity: 1 }],
        diningHall: { en: 'Boys Hall', fa: 'سالن سلف پسران' },
        deliveryFee: 0,
        total: 80000,
        status: OrderFlowStatus.DELIVERED,
        timestamp: Date.now() - 7200000, // 2 hours ago
        restaurantName: { en: 'Self Service', fa: 'سلف دانشگاه' },
        customerPhone: '09354445566',
    },
];

export const DELIVERY_LOCATIONS_DATA: DeliveryLocation[] = [
  { id: 'energy-faculty', name: { en: 'Energy Engineering Faculty', fa: 'دانشکده مهندسی انرژی' }, fee: 30000 },
  { id: 'management-faculty', name: { en: 'Management & Economics Faculty', fa: 'دانشکده مدیریت و اقتصاد' }, fee: 30000 },
  { id: 'civil-faculty', name: { en: 'Civil Engineering Faculty', fa: 'دانشکده مهندسی عمران' }, fee: 25000 },
  { id: 'physics-faculty', name: { en: 'Physics Faculty', fa: 'دانشکده فیزیک' }, fee: 20000 },
  { id: 'math-faculty', name: { en: 'Mathematical Sciences Faculty', fa: 'دانشکده علوم ریاضی' }, fee: 20000 },
  { id: 'chemistry-faculty', name: { en: 'Chemistry Faculty', fa: 'دانشکده شیمی' }, fee: 25000 },
  { id: 'electrical-faculty', name: { en: 'Electrical Engineering Faculty', fa: 'دانشکده مهندسی برق' }, fee: 20000 },
  { id: 'industrial-faculty', name: { en: 'Industrial Engineering Faculty', fa: 'دانشکده مهندسی صنایع' }, fee: 20000 },
  { id: 'chem-pet-faculty', name: { en: 'Chemical & Petroleum Eng. Faculty', fa: 'دانشکده مهندسی شیمی و نفت' }, fee: 15000 },
  { id: 'materials-faculty', name: { en: 'Materials Science & Eng. Faculty', fa: 'دانشکده مهندسی و علم مواد' }, fee: 25000 },
  { id: 'mechanical-faculty', name: { en: 'Mechanical Engineering Faculty', fa: 'دانشکده مهندسی مکانیک' }, fee: 30000 },
  { id: 'computer-faculty', name: { en: 'Computer Engineering Faculty', fa: 'دانشکده مهندسی کامپیوتر' }, fee: 15000 },
  { id: 'aero-faculty', name: { en: 'Aerospace Engineering Faculty', fa: 'دانشکده مهندسی هوا فضا' }, fee: 30000 },
  { id: 'test-management', name: { en: 'Test Management Department', fa: 'مدیریت تست بدز' }, fee: 30000 },
  { id: 'physical-education-management', name: { en: 'Physical Education Management', fa: 'مدیریت تربیت بدنی' }, fee: 20000 },
  { id: 'linguistics-center', name: { en: 'Linguistics Center', fa: 'مرکز زبان شناسی' }, fee: 10000 },
  { id: 'philosophy-group', name: { en: 'Philosophy of Science Group', fa: 'گروه فلسفه علم' }, fee: 25000 },
  { id: 'maaref-center', name: { en: 'Maaref Center', fa: 'مرکز معارف' }, fee: 10000 },
  { id: 'engineering-skills-center', name: { en: 'Engineering Skills Training Center', fa: 'مرکز آموزش مهارت‌های مهندسی' }, fee: 10000 },
  { id: 'ahmadi-roshan-dorm', name: { en: 'Ahmadi Roshan Dormitory', fa: 'خوابگاه احمدی روشن' }, fee: 45000 },
  { id: 'tarasht2-dorm', name: { en: 'Tarasht 2 Dormitory', fa: 'خوابگاه طرشت 2' }, fee: 50000 },
  { id: 'tarasht3-dorm', name: { en: 'Tarasht 3 Dormitory', fa: 'خوابگاه طرشت 3' }, fee: 45000 },
  { id: 'ibn-sina-building', name: { en: 'Ibn Sina Building', fa: 'ساختمان ابن سینا' }, fee: 10000 },
  { id: 'halls', name: { en: 'Auditoriums', fa: 'تالارها' }, fee: 25000 },
  { id: 'science-tech-park', name: { en: 'Science & Technology Park', fa: 'پارک علم و فناوری' }, fee: 20000 },
  { id: 'mosque', name: { en: 'Mosque', fa: 'مسجد' }, fee: 25000 },
  { id: 'education-building', name: { en: 'Education Building', fa: 'ساختمان آموزش' }, fee: 30000 },
  { id: 'amphitheater', name: { en: 'Amphitheater', fa: 'آمفی تئاتر' }, fee: 25000 },
];